### ISSUE TITLE
Error to load solutions

### ISSUE THREAD

**Issue by Fredylon** [watson-developer-cloud/visual-recognition-aspnet#12]
error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\xxxxxxx\Source\Repos\visual-recognition-aspnet\src\WatsonServices\WatsonServices.csproj

**Comment by degrim** [comment]
@Fredylon Which version of Visual Studio are you using?  This sample is intended to be used with VS 2017 or VS 2017 for Mac.  Earlier versions will not be able to open or run it because it uses the new MSBuild format for .NET Core.

**Comment by Fredylon** [comment]
You are right, I was used VS 2015. I will use with VS 2017. Thanks at lot.

**Comment by degrim** [comment]
Closing this, as the issue was resolved.
